In [2]:
import numpy as np
v = np.array([1,2,3])

In [3]:
v.shape

(3,)

In [4]:
v[:,np.newaxis]

array([[1],
       [2],
       [3]])

In [5]:
w = np.expand_dims(v,axis=0)

In [6]:
w

array([[1, 2, 3]])

In [7]:
w.shape

(1, 3)

In [8]:
w2 = np.expand_dims(v,axis=1)

In [9]:
w2

array([[1],
       [2],
       [3]])

In [10]:
w2 = np.expand_dims(v,axis=-1)

In [11]:
w2

array([[1],
       [2],
       [3]])